// src/lib/auditActions.ts
export const AUDIT_ACTIONS = [
  { value: "auth:login", label: "Login" },
  { value: "auth:logout", label: "Logout" },
  { value: "auth:password_reset", label: "Password Reset" },
  { value: "user:create", label: "User Create" },
  { value: "user:view", label: "User View" },
  { value: "user:modify", label: "User Modify" },
  { value: "user:delete", label: "User Delete" },
  { value: "user:activate", label: "User Activate" },
  { value: "user:deactivate", label: "User Deactivate" },
  { value: "role:create", label: "Role Create" },
  { value: "role:view", label: "Role View" },
  { value: "role:modify", label: "Role Modify" },
  { value: "role:delete", label: "Role Delete" },
  { value: "merchant:create", label: "Merchant Create" },
  { value: "merchant:view", label: "Merchant View" },
  { value: "merchant:modify", label: "Merchant Modify" },
  { value: "merchant:delete", label: "Merchant Delete" },
  { value: "shortcode:create", label: "Shortcode Create" },
  { value: "shortcode:view", label: "Shortcode View" },
  { value: "shortcode:modify", label: "Shortcode Modify" },
  { value: "shortcode:delete", label: "Shortcode Delete" },
  { value: "shortcode:assign", label: "Shortcode Assign" },
  { value: "service:create", label: "Service Create" },
  { value: "service:view", label: "Service View" },
  { value: "service:modify", label: "Service Modify" },
  { value: "service:delete", label: "Service Delete" },
  { value: "service:assign_shortcode", label: "Assign Shortcode" },
  { value: "configuration:create", label: "Configuration Create" },
  { value: "configuration:view", label: "Configuration View" },
  { value: "configuration:modify", label: "Configuration Modify" },
  { value: "configuration:delete", label: "Configuration Delete" },
];
